import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "../_contexts/UserContext";
import AppChrome from "@/_components/AppChrome";

export const metadata: Metadata = {
  title: "Tether",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <UserProvider>
          <AppChrome>{children}</AppChrome>
        </UserProvider>
      </body>
    </html>
  );
}
